# Generated by Django 6.0.3 on 2026-04-07 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_receptionistprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('PATIENT', 'Patient'), ('DOCTOR', 'Doctor'), ('RECEPTIONIST', 'Receptionist'), ('ADMIN', 'Admin'), ('TO_BE_ADMIN', 'To Be Admin')], max_length=20),
        ),
    ]
