# Generated by Django 6.0.3 on 2026-04-14 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_doctorprofile_session_price_alter_doctorprofile_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='doctors/profile_pics/'),
        ),
    ]
